// Auto-generated by `loft generate`. Fill in the todo!() bodies.
// Functions with text parameters use loft_ffi helpers.
// Struct field offsets are in *_fields modules.

#![allow(clippy::missing_safety_doc)]

// Add to Cargo.toml: loft-ffi = { path = "../../../loft-ffi" }

#[unsafe(no_mangle)]
pub extern "C" fn n_tcp_listen(port: i32) -> i32 {
    todo!("implement n_tcp_listen(port)")
}

#[unsafe(no_mangle)]
pub extern "C" fn n_tcp_accept(handle: i32) -> bool {
    todo!("implement n_tcp_accept(handle)")
}

#[unsafe(no_mangle)]
pub extern "C" fn n_tcp_method() -> loft_ffi::LoftStr {
    let result: String = todo!("implement n_tcp_method()");
    loft_ffi::ret(result)
}

#[unsafe(no_mangle)]
pub extern "C" fn n_tcp_path() -> loft_ffi::LoftStr {
    let result: String = todo!("implement n_tcp_path()");
    loft_ffi::ret(result)
}

#[unsafe(no_mangle)]
pub extern "C" fn n_tcp_body() -> loft_ffi::LoftStr {
    let result: String = todo!("implement n_tcp_body()");
    loft_ffi::ret(result)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_tcp_respond(status: i32, body_ptr: *const u8, body_len: usize) {
    let body = unsafe { loft_ffi::text(body_ptr, body_len) };
    todo!("implement n_tcp_respond(status, body)")
}

#[unsafe(no_mangle)]
pub extern "C" fn n_tcp_close(handle: i32) {
    todo!("implement n_tcp_close(handle)")
}

#[unsafe(no_mangle)]
pub extern "C" fn n_ws_upgrade() -> i32 {
    todo!("implement n_ws_upgrade()")
}

#[unsafe(no_mangle)]
pub extern "C" fn n_ws_recv(handle: i32) -> bool {
    todo!("implement n_ws_recv(handle)")
}

#[unsafe(no_mangle)]
pub extern "C" fn n_ws_message() -> loft_ffi::LoftStr {
    let result: String = todo!("implement n_ws_message()");
    loft_ffi::ret(result)
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_ws_send(handle: i32, msg_ptr: *const u8, msg_len: usize) -> bool {
    let msg = unsafe { loft_ffi::text(msg_ptr, msg_len) };
    todo!("implement n_ws_send(handle, msg)")
}

#[unsafe(no_mangle)]
pub extern "C" fn n_ws_close(handle: i32) {
    todo!("implement n_ws_close(handle)")
}
