// Auto-generated by `loft generate`. Fill in the todo!() bodies.
// Functions with text parameters use loft_ffi helpers.
// Struct field offsets are in *_fields modules.

#![allow(clippy::missing_safety_doc)]

// Add to Cargo.toml: loft-ffi = { path = "../../../loft-ffi" }

#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_http_do(
    method_ptr: *const u8, method_len: usize,
    url_ptr: *const u8, url_len: usize,
    body_ptr: *const u8, body_len: usize,
    headers_ptr: *const u8, headers_len: usize,
) -> i32 {
    let method = unsafe { loft_ffi::text(method_ptr, method_len) };
    let url = unsafe { loft_ffi::text(url_ptr, url_len) };
    let body = unsafe { loft_ffi::text(body_ptr, body_len) };
    let headers = unsafe { loft_ffi::text(headers_ptr, headers_len) };
    todo!("implement n_http_do(method, url, body, headers)")
}

#[unsafe(no_mangle)]
pub extern "C" fn n_http_body() -> loft_ffi::LoftStr {
    let result: String = todo!("implement n_http_body()");
    loft_ffi::ret(result)
}
